#INITIAL SETTINGS
data_source:
  directory:
  filename:
  column_names:
  drop_columns:
  target_name:
  test_size:
  random_state:


#kNN parameters
model:
  n_neighbors:
  weights:
  algorithm:
  leaf_size:
  p:
  metric:
  n_jobs:
  model_directory:
  model_name: